---
config:
  # -- Defines the `namespaceSelector`/`objectSelector` in the webhook configurations.
  # The Kyverno namespace is excluded if `excludeKyvernoNamespace` is `true` (default)
  webhooks:
    # Exclude namespaces
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-system
        - kyverno
  excludeKyvernoNamespace: true
  resourceFiltersExcludeNamespaces:
  - kube-system
  - kyverno
  - harbor

admissionController:
  replicas: 3

backgroundController:
  replicas: 2

cleanupController:
  replicas: 2

reportsController:
  replicas: 2
